backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 10;
shadow-opacity = 0.65;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-color = "#000000";

shadow-exclude = [
    "class_g = 'i3-frame'",
    "class_g = 'Polybar'",
    "class_g = 'Rofi'",
    "window_type = 'menu'",
    "window_type = 'dropdown_menu'",
    "window_type = 'popup_menu'",
    "window_type = 'tooltip'",
    "window_type = 'utility'",
    "class_g = 'slop'",
    "_NET_WM_STATE@:a *= '_NET_WM_STATE_FULLSCREEN'"
];

fading = true;
fade-in-step = 0.5;
fade-out-step = 0.5;
fade-delta = 4;
no-fading-openclose = false;
no-fading-destroyed-argb = true;

fade-exclude = [
    "class_g = 'slop'",
    "class_g = 'maim'"
];

opacity-rule = [
    "85:class_g = 'st' && focused",
    "75:class_g = 'st' && !focused",
    "100:class_g = 'librewolf'",
    "100:class_g = 'Rofi'",
    "100:class_g = 'maim'",
    "100:class_g = 'i3lock'",
    "100:class_g = 'i3lock-fancy'",
    "100:window_type = 'dock'",
    "100:window_type = 'desktop'",
    "100:class_g = 'sober'",
    "100:class_g = 'org.vinegarhq.Sober'",    
    "100:class_g = 'Terraria'",
    "100:class_g = 'Terraria.bin.x86_64'",
    "100:class_g = 'Terraria.bin.x86_64'",
    "100:class_g = 'tModLoader.bin.x86_64'",
    "100:class_g = 'dotnet'",
    "95:class_g = 'Google-chrome' && focused",
    "80:class_g = 'Google-chrome' && !focused",
    "95:class_g = 'Steam' && focused",
    "90:class_g = 'Steam' && !focused",
    "100:class_g = 'steam_app_0' && focused", # General rule for games
    "100:class_g = 'steam_app_0' && !focused",
    "100:class_g = 'Minecraft* 1.20.1'"
];

blur-method = "dual_kawase";
blur-strength = 3; 

blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "class_g = 'Rofi'",
    "class_g = 'i3lock'",
    "class_g = 'maim'",
    "class_g = 'slop'",
    "_GTK_FRAME_EXTENTS@:c"
];

corner-radius = 10;
rounded-corners-exclude = [
    "class_g = 'i3bar'",
    "class_g = 'dmenu'",
    "class_g = 'i3lock'",
    "class_g = 'i3lock-fancy'",
    "window_type = 'dock'",
    "window_type = 'desktop'"
];

active-opacity = 0.90;
inactive-opacity = 0.80;
detect-client-opacity = true;
use-damage = true;
